### ISSUE TITLE
GuzzleHttp version

### ISSUE THREAD

**Issue by spbentz** [SURFnet/yubikey-api-client#1]
GuzzleHttp version 4.2.3 is not the current version and it's no more documented. Could you upgrade to version 5.3 (@see http://docs.guzzlephp.org/en/5.3/index.html) or to version 6, the latest stable version (@see http://docs.guzzlephp.org/en/stable/) ?

**Comment by DRvanR** [comment]
Hello,

great suggestion, would be even better if you could create a PR for this :wink: I myself will not have time to do this in the foreseeable future.

**Comment by galphanet** [comment]
I see `"guzzlehttp/guzzle": "^6.0",` in the `composer.json`. Can we assume this was done ?

**Comment by thijskh** [comment]
Yes, see #5.
